apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: larimia-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: larimia-api
  minReplicas: 3
  maxReplicas: 12
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
